name: Sync Upstream Repository

on:
  schedule:
    # 每天 UTC 时间 00:00 (北京时间 08:00) 自动运行
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/ls125781003/tvboxtg.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main
          git merge upstream/main --no-edit
          git push origin main
